wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.6.12
      5: 0.10.15
artifact_dir:
  desc: null
  value: ./artifacts/
home_dir:
  desc: null
  value: .
mode:
  desc: null
  value: student
n_jobs:
  desc: null
  value: -1
no_betas:
  desc: null
  value: 100
no_samples:
  desc: null
  value: 2500
seed:
  desc: null
  value: 1
